### ISSUE TITLE
.obj file required

### ISSUE THREAD

**Issue by billy9222** [zeitraumdev/iPadLIDARScanExport#1]
Hi,

Thats great you are following this technology on a very early stages. I was doing some R&D on this and realised that I could opt LIDAR Apple as my final year project, I am still new to this. Could you please share a reference obj file with me? I am just curious how would it look like before going any further.

Its not an issue but I couldn't find any other way to contact you. :D 

Best Regards,
Bilal 
University of Kiel

**Comment by sp-zeitraum** [comment]
Hello Bilal,

I sent you an E-Mail regarding your request.

Greetings,
Stefan
