### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by zackify** [zeitraumdev/iPadLIDARScanExport#2]
Thank you so much for this code and your blog post. It is helping me learn a lot about ARKIt.

I had a question for you, curious if you have any plans to adapt your code to this ARKIt 4 point cloud demo: https://developer.apple.com/documentation/arkit/visualizing_a_point_cloud_using_scene_depth

I am going to attempt this myself but I'm very new to Swift + AR Kit. I am hoping I can reference what you wrote to export the colored point cloud that that sample project gives you.

**Comment by sp-zeitraum** [comment]
Hi @zackify,
thank you for reaching out. I'm glad, that the repo & article are helping you.
Currently we have no plans for further research in that direction, but maybe in the future.
